# --------------------------------------------------
# Site settings
# --------------------------------------------------
  
# Color
color:
  default: "#33333D"
  link: "#FFBE5B"

# Background Image
background_image:

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Preview
preview:
  enable: true
  model: wave  #cloud
  welcome_image: /images/theme/welcome-image.jpg
  motto:
    default: 我在开了灯的床头下，想问问自己的心啊。
    color: '#000000'
    api:  #'http://localhost:3000/api/motto'

# Menu
menu:
  home: / || 首页
  galleries: /galleries || 摄影
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=894519210 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/izhaoo || icongithub-fill || '#24292E'
  email: mailto:izhaoo@163.com || iconmail

# Fab (FloatActionButton)
fab:
  enable: true
  alwaysShow: false

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post settings
# --------------------------------------------------

# Post image
post_image: /images/theme/post-image.jpg

# Donate
donate:
  enable: true
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html #markdown text

# --------------------------------------------------
# Page settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# --------------------------------------------------
# Comment settings
# --------------------------------------------------

comments:
  enable: true
  type: valine
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId:
  appKey:
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  appKey:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Daovoice
daovoice:
  enable: true
  appId: abcdefg  # app_id

# Lazyload
lazyload:
  enable: true
  onlyPost: false
  loadingImage: /images/theme/loading.gif

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight: true

# --------------------------------------------------
# Script settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/xcode.min.css
  iconfont_css: //at.alicdn.com/t/font_1445822_hhodbqn7tit.css

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: #id
  google: #id
  tencent: #id
  cnzz: #id

# Custom
custom:
  head:
  foot:
  css:
  js:
