# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || 首页
  galleries: /galleries/ || 摄影
  archives: /archives/ || 归档
  tags: /tags/ || 标签
  categories: /categories/ || 分类
  about: /about/ || 关于

# Color
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'
  link-gradient: 'linear-gradient(-60deg, #ff5858 0%, #f09819 100%)'

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Font
font:
  size: 14px
  family:

# Background Image
background_image:

# Loading
loading:
  gif: /images/theme/loading.gif
  lottie:

# Preview
preview:
  enable: true
  type: wave  # wave | cloud
  background:
    type: image # image video
    default_image:
      light: /images/theme/welcome-image.jpg
      dark: /images/theme/welcome-image.jpg
    video:
    api: # https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: 我在开了灯的床头下，想问问自己的心啊。
    color: '#ffffff'
    typing: true
    api: https://v2.jinrishici.com/one.json
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true
  back_home: true

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=894519210 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/zhaoo || icongithub-fill || '#9f7be1'
  email: mailto:izhaoo@163.com || iconmail

# Override Scrollbar
scrollbar:
  type: default # default | simple | normal | none

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# Search
search:
  enable: false

# QR Code
qrcode:
  enable: true
  type: url # url | image
  image: https://pic.izhaoo.com/weapp-code.jpg

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Excerpt
excerpt: 
  enable: true

# Post Image
post_image:
  random: local # local galleries
  default: /images/theme/post-image.jpg

# Page Size
post_page_size:
  width: 800px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate
donate:
  enable: true
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography
  type: waterfall # waterfall | grid
  columns: 3


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: false
  type: valine # gitalk | valine | changyan
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId:
  appKey:
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading:
    gif: /images/theme/loading.gif
    lottie:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: # id
  google: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://code.jquery.com/jquery-3.6.0.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://cdn.bootcdn.net/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  lottie_js: https://cdn.bootcdn.net/ajax/libs/lottie-web/5.7.12/lottie.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: https://at.alicdn.com/t/font_1445822_p6ry5n7lrr.css

# Custom
custom:
  head:
  foot:
  css:
  js:
